### ISSUE TITLE
Won't build

### ISSUE THREAD

**Issue by David-Else** [jamesseanwright/ts-pac-man#2]
Thanks for this fantastic resource, and great talk! Afraid it won't build. I do `pnpm install`, `build` and I get:
```
rollup -c --prod && npm run copy-static

(!) You have passed an unrecognized option
Unknown CLI flag: prod. Allowed options: acorn, acornInjectPlugins, amd, assetFileNames, banner, c, cache, chunkFileNames, chunkGroupingSize, compact, config, context, d, dir, dynamicImportFunction, e, entryFileNames, environment, esModule, experimentalCacheExpiry, experimentalOptimizeChunks, experimentalTopLevelAwait, exports, extend, external, f, file, footer, format, freeze, g, globals, h, i, indent, inlineDynamicImports, input, interop, intro, m, manualChunks, moduleContext, n, name, namespaceToStringTag, noConflict, o, onwarn, outro, paths, perf, plugins, preferConst, preserveModules, preserveSymlinks, shimMissingExports, silent, sourcemap, sourcemapExcludeSources, sourcemapFile, strict, strictDeprecations, treeshake, v, w, watch

src/index.ts → dist...
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
src/index.ts
44:     return rAF;
45: };
46: (() => tslib_1.__awaiter(this, void 0, void 0, function* () {
                             ^
47:     const playAudio = yield createAudioPlayer(new AudioContext(), '/audio/chase.mp3');
48:     const sprites = yield loadSpriteSheet();
[!] (plugin rpt2) Error: /home/david/sites/TypeScript/ts-pac-man/src/audio.ts(13,67): semantic error TS2354: This syntax requires an imported helper but module 'tslib' cannot be found.
src/audio.ts
Error: /home/david/sites/TypeScript/ts-pac-man/src/audio.ts(13,67): semantic error TS2354: This syntax requires an imported helper but module 'tslib' cannot be found.
    at error (/home/david/sites/TypeScript/ts-pac-man/node_modules/.pnpm/registry.npmjs.org/rollup/1.17.0/node_modules/rollup/dist/rollup.js:9408:30)
    at Object.error (/home/david/sites/TypeScript/ts-pac-man/node_modules/.pnpm/registry.npmjs.org/rollup/1.17.0/node_modules/rollup/dist/rollup.js:15659:24)
    at Object.error (/home/david/sites/TypeScript/ts-pac-man/node_modules/.pnpm/registry.npmjs.org/rollup/1.17.0/node_modules/rollup/dist/rollup.js:16099:38)
    at RollupContext.error (/home/david/sites/TypeScript/ts-pac-man/node_modules/.pnpm/registry.npmjs.org/rollup-plugin-typescript2/0.22.1_rollup@1.17.0+typescript@3.5.3/node_modules/rollup-plugin-typescript2/src/rollupcontext.ts:37:18)
    at /home/david/sites/TypeScript/ts-pac-man/node_modules/.pnpm/registry.npmjs.org/rollup-plugin-typescript2/0.22.1_rollup@1.17.0+typescript@3.5.3/node_modules/rollup-plugin-typescript2/src/print-diagnostics.ts:41:11
    at arrayEach (/home/david/sites/TypeScript/ts-pac-man/node_modules/.pnpm/registry.npmjs.org/rollup-plugin-typescript2/0.22.1_rollup@1.17.0+typescript@3.5.3/node_modules/rollup-plugin-typescript2/node_modules/lodash/lodash.js:516:11)
    at _.each (/home/david/sites/TypeScript/ts-pac-man/node_modules/.pnpm/registry.npmjs.org/rollup-plugin-typescript2/0.22.1_rollup@1.17.0+typescript@3.5.3/node_modules/rollup-plugin-typescript2/node_modules/lodash/lodash.js:9342:14)
    at printDiagnostics (/home/david/sites/TypeScript/ts-pac-man/node_modules/.pnpm/registry.npmjs.org/rollup-plugin-typescript2/0.22.1_rollup@1.17.0+typescript@3.5.3/node_modules/rollup-plugin-typescript2/src/print-diagnostics.ts:9:2)
    at Object.transform (/home/david/sites/TypeScript/ts-pac-man/node_modules/.pnpm/registry.npmjs.org/rollup-plugin-typescript2/0.22.1_rollup@1.17.0+typescript@3.5.3/node_modules/rollup-plugin-typescript2/src/index.ts:225:5)
    at /home/david/sites/TypeScript/ts-pac-man/node_modules/.pnpm/registry.npmjs.org/rollup/1.17.0/node_modules/rollup/dist/rollup.js:15806:25

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ts-pac-man@0.0.1 build: `rollup -c --prod && npm run copy-static`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ts-pac-man@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/david/.npm/_logs/2020-03-07T16_17_27_699Z-debug.log
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```
If I remove the mysterious `--prod` that I can find no reference for I still get the other errors.

Rollup's new official TS plugin has come on leaps and bounds recently, you might like to check it out https://github.com/rollup/plugins/blob/master/packages/typescript/CHANGELOG.md

**Comment by jamesseanwright** [comment]
Hey @David-Else,

Thanks for raising this. It seems that I never noticed this as I was running the project in dev mode (i.e. `npm run dev`), which invokes the Rollup config directly with a hard-coded `prod` argument of `false`. However, when building the _production_ bundle (with `npm build`), I do indeed see the same error.

You can't find any documentation on the `--prod` argument because it's a _custom option_. However, it would seem that this feature:

* is no longer documented
* [has known issues](https://github.com/rollup/rollup/issues/2694)

I've therefore dropped it entirely and replaced it with a `NODE_ENV` environment variable, which should resolve the issue.

I've verified this locally, but please can you pull my latest changes (or update your fork if you've created one) and let me know if they fix the problem?

**Comment by David-Else** [comment]
Hi, I did a pull, the unknown CLI flag is sorted, but I still get the second error on `build` and `dev` scripts:
```
> NODE_ENV=production rollup -c && npm run copy-static


src/index.ts → dist...
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
src/index.ts
44:     return rAF;
45: };
46: (() => tslib_1.__awaiter(this, void 0, void 0, function* () {
                             ^
47:     const playAudio = yield createAudioPlayer(new AudioContext(), '/audio/chase.mp3');
48:     const sprites = yield loadSpriteSheet();
[!] (plugin rpt2) Error: /home/david/sites/TypeScript/ts-pac-man/src/audio.ts(13,67): semantic error TS2354: This syntax requires an imported helper but module 'tslib' cannot be found.
src/audio.ts
Error: /home/david/sites/TypeScript/ts-pac-man/src/audio.ts(13,67): semantic error TS2354: This syntax requires an imported helper but module 'tslib' cannot be found.
    at error (/home/david/sites/TypeScript/ts-pac-man/node_modules/.pnpm/registry.npmjs.org/rollup/1.17.0/node_modules/rollup/dist/rollup.js:9408:30)
    at Object.error (/home/david/sites/TypeScript/ts-pac-man/node_modules/.pnpm/registry.npmjs.org/rollup/1.17.0/node_modules/rollup/dist/rollup.js:15659:24)
    at Object.error (/home/david/sites/TypeScript/ts-pac-man/node_modules/.pnpm/registry.npmjs.org/rollup/1.17.0/node_modules/rollup/dist/rollup.js:16099:38)
    at RollupContext.error (/home/david/sites/TypeScript/ts-pac-man/node_modules/.pnpm/registry.npmjs.org/rollup-plugin-typescript2/0.22.1_rollup@1.17.0+typescript@3.5.3/node_modules/rollup-plugin-typescript2/src/rollupcontext.ts:37:18)
    at /home/david/sites/TypeScript/ts-pac-man/node_modules/.pnpm/registry.npmjs.org/rollup-plugin-typescript2/0.22.1_rollup@1.17.0+typescript@3.5.3/node_modules/rollup-plugin-typescript2/src/print-diagnostics.ts:41:11
    at arrayEach (/home/david/sites/TypeScript/ts-pac-man/node_modules/.pnpm/registry.npmjs.org/rollup-plugin-typescript2/0.22.1_rollup@1.17.0+typescript@3.5.3/node_modules/rollup-plugin-typescript2/node_modules/lodash/lodash.js:516:11)
    at _.each (/home/david/sites/TypeScript/ts-pac-man/node_modules/.pnpm/registry.npmjs.org/rollup-plugin-typescript2/0.22.1_rollup@1.17.0+typescript@3.5.3/node_modules/rollup-plugin-typescript2/node_modules/lodash/lodash.js:9342:14)
    at printDiagnostics (/home/david/sites/TypeScript/ts-pac-man/node_modules/.pnpm/registry.npmjs.org/rollup-plugin-typescript2/0.22.1_rollup@1.17.0+typescript@3.5.3/node_modules/rollup-plugin-typescript2/src/print-diagnostics.ts:9:2)
    at Object.transform (/home/david/sites/TypeScript/ts-pac-man/node_modules/.pnpm/registry.npmjs.org/rollup-plugin-typescript2/0.22.1_rollup@1.17.0+typescript@3.5.3/node_modules/rollup-plugin-typescript2/src/index.ts:225:5)
    at /home/david/sites/TypeScript/ts-pac-man/node_modules/.pnpm/registry.npmjs.org/rollup/1.17.0/node_modules/rollup/dist/rollup.js:15806:25

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ts-pac-man@0.0.1 build: `NODE_ENV=production rollup -c && npm run copy-static`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ts-pac-man@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/david/.npm/_logs/2020-03-11T21_24_43_782Z-debug.log
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```
Could `pnpm` somehow be involved? Here is my output from `pnpm ls` confirming dependencies:
```
pnpm ls
Legend: production dependency, optional only, dev only

ts-pac-man@0.0.1 /home/david/sites/TypeScript/ts-pac-man

devDependencies:
@types/jest 24.0.16
jest 24.8.0
node-static 0.7.11
prettier 1.18.2
rollup 1.17.0
rollup-plugin-node-resolve 5.2.0
rollup-plugin-terser 5.1.1
rollup-plugin-typescript2 0.22.1
ts-jest 24.0.2
typescript 3.5.3$ 
```

**Comment by jamesseanwright** [comment]
That's odd, as it works fine on my end. `tslib` is a dependency that's pulled in by `rollup-plugin-typescript2`:

```sh
$ npm ls tslib
ts-pac-man@0.0.1 /Users/jameswright/dev/ts-pac-man
└─┬ rollup-plugin-typescript2@0.22.1
  └── tslib@1.10.0
```

Please could you try `pnpm ls tslib` and tell me if `tslib` is output in the dependency tree?

**Comment by David-Else** [comment]
I typed `pnpm ls tslib` and got nothing, so it seemed not installed. I then installed `tslib` with `pnpm i --save-dev tslib`, but still get an error on build:

```
NODE_ENV=production rollup -c && npm run copy-static


src/index.ts → dist...
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
src/index.ts
44:     return rAF;
45: };
46: (() => tslib_1.__awaiter(this, void 0, void 0, function* () {
                             ^
47:     const playAudio = yield createAudioPlayer(new AudioContext(), '/audio/chase.mp3');
48:     const sprites = yield loadSpriteSheet();
src/audio.ts
1: import * as tslib_1 from "tslib";
2: const mapToPromises = (items, cb) => Promise.all(items.map(cb));
3: export const audioPlayerCreator = (fetch) => (audioContext, ...paths) => tslib_1.__awaiter(this, void 0, void 0, function* () {
                                                                                              ^
4:     const responses = yield mapToPromises(paths, path => fetch(path));
5:     const arrayBuffers = yield mapToPromises(responses, res => res.arrayBuffer());
src/spriteSheet.ts
1: import * as tslib_1 from "tslib";
2: export const spriteSheetCreator = (createBitmapImage) => {
3:     return (sheet, definitions) => tslib_1.__awaiter(this, void 0, void 0, function* () {
                                                        ^
4:         const sprites = yield Promise.all(definitions.map(([, dimensions]) => createBitmapImage(sheet, ...dimensions)));
5:         return new Map(definitions.map(([name], i) => [name, sprites[i]]));
created dist in 2.2s

> ts-pac-man@0.0.1 copy-static /home/david/sites/TypeScript/ts-pac-man
> bash -c 'cp -r src/{index.html,images,audio} dist'
```

**Comment by jamesseanwright** [comment]
Is this causing the build to fail? I'm seeing the same thing, but it still produces the distributable. Let me see if I can configure this properly nonetheless.

**Comment by jamesseanwright** [comment]
It seems this is a warning, but I've set the `context` config option to `window`, given that's the top-level context for client-side JavaScript. The development and production builds are unaffected, and the warning no longer emits during build.

**Comment by David-Else** [comment]
Cheers! With the latest version it compiles, but to make it actually load resources it needs the following lines changing:
```
src="index.js"
./audio/chase.mp3
./images/spritesheet.png'
```

the `/` does not work, it needs to be `./` for current directory running from a dev server. I am on Linux... could this be the cause?

The game is playing, but I am afraid PacMan goes through walls and can't be killed. How ready is the game?

The reason I am interested in this is I am trying to design the most simple but perfect game engine known to humanity :) I see your composition style is a bit different to what I am using. I am going to produce a Udemy course on TypeScript, so am getting pretty OCD about it at the moment. 

I want each entity to have a set of components that give them:
- an `update()` method to run whatever is needed on each tick
- local state (for things like colour, position etc)
- global state injected in only for items that need it, including a pub sub system

I want it as simple as possible to be used as a lesson in composition. Most examples of entity component systems are too complex for what I am after.

This is my current idea for my main pattern for the entities:
```ts
/**
 * Delegate
 */
interface Delegate {
  update(): void;
}

class Entity {
  private readonly delegates: Delegate[];

  constructor(...delegates: Delegate[]) {
    this.delegates = delegates;
  }

  public update(): void {
    for (const delegate of this.delegates) {
      delegate.update();
    }
  }
}

/**
 * Components
 */
export class ComponentOne implements Delegate {
  constructor(
    private readonly globalState: object,
    private readonly entityState: EntityState
  ) {}
  public update(): void {
    console.log(this.entityState, this.globalState);
  }
}

export class ComponentTwo implements Delegate {
  constructor(private readonly entityState: EntityState) {}
  update(): void {
    console.log("Hello from ComponentTwo");
  }
}

/**
 * Entity
 */
class EntityState {
  constructor(public entityState: object) {}
}

const createEntity = ({
  globalState,
  data
}: {
  globalState: object;
  data: object;
}): Entity => {
  const entityState = new EntityState(data);

  return new Entity(
    new ComponentOne(globalState, entityState),
    new ComponentTwo(entityState)
  );
};

const entityOne = createEntity({
  globalState: { global: "This is the global state" },
  data: { entityState: "This is entityOne local state" }
});
entityOne.update();

const obj: { run(hello): void } = {
  run(hello) {}
};
```
Don't worry about commenting on this if you are busy, just thought I would mention it out of interest. All the best!

**Comment by jamesseanwright** [comment]
> the / does not work, it needs to be ./ for current directory running from a dev server. I am on Linux... could this be the cause?

This isn't right; those paths are neither Node.js nor Unix paths, but are relative URLs, [served by the dev server](https://github.com/jamesseanwright/ts-pac-man/blob/3c9eaebbb754eb955941f1992b9f7b80ce40cf8d/tasks/dev.js#L12). Said URLs are then loaded by the game [via the fetch API](https://github.com/jamesseanwright/ts-pac-man/blob/3c9eaebbb754eb955941f1992b9f7b80ce40cf8d/src/audio.ts#L17). This might be able to handle the `./` prefix, but for a relative URL, `/` is the typical lead character.

> The game is playing, but I am afraid PacMan goes through walls and can't be killed. How ready is the game?

Regrettably, I was unable to complete the game before my talk. I'm aiming to return to it later in the year to add health and entity state to Pac-Man, as well as improving movement and collision within my grid system. I was able to show the core tenets of 2D games dev, but in terms of completeness it's barely an alpha at this point.

> The reason I am interested in this is I am trying to design the most simple but perfect game engine known to humanity :) I see your composition style is a bit different to what I am using. I am going to produce a Udemy course on TypeScript, so am getting pretty OCD about it at the moment.

It's extremely interesting that you bring this up; I've originally followed the sort of approach you've described :) I gave [a talk on my approach at FrontCon 2018](https://www.youtube.com/watch?v=HbbnTAHY7jg), although I build an Canvas-based visualisation instead of an interactive game; the core principles nonetheless apply. It's actually this paradigm that pushed me towards the more functional approach my Pac-Man implementation follows (i.e. systems are pure functions that act upon data-containing components), which I personally find a great deal less verbose. Although there's a lot of underlying logic around component registration, this is well abstracted and could even sit within a library, allowing the user to write most of their game logic as reusable, testable functions; from a consumer perspective in particular, I'd say this approach is vastly less verbose than having to instantiate classes across the board.

Maybe there's a middle-ground: generic entity containers that hold a collection of functions as their delegates :)

**Comment by David-Else** [comment]
I am opening the `index.html` file from inside the `dist` directory using live-server. I didn't think to use any supplied dev server, I am probably too set in my ways! It certainly works fine with the modifications I mentioned and just 404's with `/` as the lead character, I thought that was relative to the root? I am probably getting muddled up, I don't have much back end experience.

LOL, it was your video I got the idea for the delegate from! I did not recognize you in the second newer video. I have been reading https://gameprogrammingpatterns.com/ as my main influence, but all the examples are in c++. I can't find many good examples of composition in TS that are not either 'enterprise' Java style or just not very good. A lot of the JS examples are not even composition but seem to think they are... it is a strange state in tutorial world. This https://www.youtube.com/watch?v=wfMtDGfHWpA video is the top search result, but it bad information as it is mixins it would seem.

I am going to have a better look at your pac-man game, and think more about the most suitable pattern for my course. Would it be OK to check back with you in the future on this subject? Maybe I could drop you an email? Would be fantastic to get some feedback.

**Comment by jamesseanwright** [comment]
That's pretty odd, as the static server that's bootstrapped by the `dev` task is configured to [serve everything under the `dist` dir](https://github.com/jamesseanwright/ts-pac-man/blob/3c9eaebbb754eb955941f1992b9f7b80ce40cf8d/tasks/dev.js#L12), which is [invoked by a standard Node HTTP server](https://github.com/jamesseanwright/ts-pac-man/blob/3c9eaebbb754eb955941f1992b9f7b80ce40cf8d/tasks/dev.js#L19); this means that everything in the `dist` dir is relative to `http://localhost:8080/` e.g. `./dist/index.js` => `http://localhost:8080/index.js` => `/index.js`. I've tried this across both macOS and Linux and haven't had any isues with it.

It's a small world, right? 😉 That's why I prefer my newer approach over the class delegate pattern I described in my first talk; I felt it was too reminicent of entreprise Java, although I'm perhaps being too harsh on myself. I wouldn't necessarily say that Fun Fun Function's video is wrong; mixins are certainly a form of composition.

I'd certainly be interesting in hearing from you as your project progresses; you can reach me via the email address on my profile 😊
